prova builder zap 2.0

diff --git a/.github/workflows/zap_dast.yml b/.github/workflows/zap_dast.yml
--- a/.github/workflows/zap_dast.yml
+++ b/.github/workflows/zap_dast.yml
@@ -20,7 +20,13 @@ jobs:
               run: |
                 docker build -t juicyshop:local .
                 docker run -d -p 3000:3000 juicyshop:local
-                timeout 60s bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 5; done'
+                echo "attendo che juice sia online"
+                if ! timeout 180s bash -c 'until curl -s http://localhost:3000 > /dev/null; do sleep 5; done'; then
+                echo "TIME OUT con errore 124 non ha risposto in tempo"
+                docker logs juice-app
+                exit 1
+                fi
+                
                 echo "Juice shop si è buildato correttamente"
 
             
